<?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Meus Albuns';
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="btn btn-primary" href="<?php echo $this->url('album', array('action'=>'add'));?>">Adicionar um novo album</a>
</p>

<table class="table">
    <tr>
        <th>Título</th>
        <th>Artista</th>
        <th>Ação</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->title);?></td>
            <td><?php echo $this->escapeHtml($album->artist);?></td>
            <td>
                <a class='btn btn-success' href="<?php echo $this->url('album',
                    array('action'=>'edit', 'id' => $album->id));?>">Editar</a>
                <a class='btn btn-danger' href="<?php echo $this->url('album',
                    array('action'=>'delete', 'id' => $album->id));?>">Deletar</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>